[package]
name = "sansio"
version = "0.0.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2024"
description = "Rust in Sans-IO"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/sansio"
homepage = "https://webrtc.rs"
repository = "https://github.com/rainliu/sansio"
keywords = ["sans-io"]
categories = [ "network-programming", "asynchronous" ]

[dependencies]
